plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def supabaseUrl = project.findProperty('SUPABASE_URL') ?: ''
def supabaseAnonKey = project.findProperty('SUPABASE_ANON_KEY') ?: ''
def kakaoNativeAppKey = project.findProperty('KAKAO_NATIVE_APP_KEY') ?: ''

android {
    namespace 'com.mdkdw1.ui.tesla'
    compileSdk 34

    defaultConfig {
        applicationId "com.mdkdw1.ui.tesla"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        buildConfigField "String", "SUPABASE_URL", ""${supabaseUrl}""
        buildConfigField "String", "SUPABASE_ANON_KEY", ""${supabaseAnonKey}""
        buildConfigField "String", "KAKAO_NATIVE_APP_KEY", ""${kakaoNativeAppKey}""
    }

    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    signingConfigs {
        release {
            def storeFilePath = System.getenv("RELEASE_STORE_FILE")
            if (storeFilePath != null) {
                storeFile file(storeFilePath)
            }
            storePassword System.getenv("RELEASE_STORE_PASSWORD")
            keyAlias System.getenv("RELEASE_KEY_ALIAS")
            keyPassword System.getenv("RELEASE_KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.security:security-crypto:1.1.0-alpha06'
    implementation 'com.kakao.maps.open:android:2.13.1'
    implementation platform('io.github.jan-tennert.supabase:bom:2.5.4')
    implementation 'io.github.jan-tennert.supabase:postgrest-kt'
    implementation 'io.github.jan-tennert.supabase:gotrue-kt'
    implementation 'io.github.jan-tennert.supabase:realtime-kt'
    implementation 'io.ktor:ktor-client-okhttp:2.3.12'
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3'
}
